module.exports = (option, context) => {
    console.log(option,context)
    option.themeConfig.sidebar={
        '/note/professionalJavascript4/':[
            '2',
            '3',
            '4',
            '5',
            '6',
            '7',
            '8',
            '9',
            '10',
            '11',
            '12',
        ],
    }
    return 
}